[build]
  command = "composer install && php -S localhost:3000"
  publish = "public"

[build.environment]
  DB_HOST = "ntsfm-ntsfm.c.aivencloud.com"
  DB_USER = "avnadmin"
  DB_NAME = "defaultdb"
  DB_PORT = "17153"

[dev]
  command = "php -S localhost:3000"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
